### PR TITLE
fix: 修复挂载目录压缩问题

### PR DESCRIPTION
**Pull request by pengfeixx**
过滤特殊字符，使用最后一个文件夹名

Bug: https://pms.uniontech.com/bug-view-163153.html
Log: 修复部分已知问题

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
