### PR TITLE
fix: don't show progress dialog on first extract

### PR DESCRIPTION
**Pull request by kt286**
fix don't show progress dialog on first extract

Log: fix don't show progress dialog on first extract

### CODE REVIEW

**Review by lhxsm — COMMENTED** [review]
I feel confused, because your title write fix the bug that do not show progessDialog on first extract , but you commit code is hide.
can you give me more detail about this?

**Comment by kt286** [comment]
> I feel confused, because your title write fix the bug that do not show progessDialog on first extract , but you commit code is hide. can you give me more detail about this?

when the progess dialog is initialized, the status is not hide. so it can't be displayed on first extract

https://github.com/linuxdeepin/deepin-compressor/blob/c6c281ee7db4bc540d8186327c8d0db4f9b273a3/src/source/mainwindow.cpp#L1187-L1189

**Comment by kt286** [comment]
maybe a better idea is change the `m_pProgressdialog->isHidden()` to `!m_pProgressdialog->isVisible()`

**Comment by lhxsm** [comment]
okay, i see what you want mean, but……actually this dialog only has two states hide or show, we haven't set visible prop.
thx for your advice.

**Review by zccrs — APPROVED** [review]

**Pull request merged**
