### PR TITLE
fix: bug 152079 152051 分卷压缩已存在判断，相应文案提示

### PR DESCRIPTION
**Pull request by myk1343**
分卷压缩已存在判断，相应文案提示

Bug: https://pms.uniontech.com/bug-view-152079.html
Log: 分卷压缩已存在判断，相应文案提示

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
