### PR TITLE
fix: 长文件解压与带软连接压缩解压

### PR DESCRIPTION
**Pull request by myk1343**
长文件解压与带软连接压缩解压

Log: 长文件解压与带软连接压缩解压

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
