### PR TITLE
fix: 修复超长文件双击打开失败的问题

### PR DESCRIPTION
**Pull request by lzwind**
修复超长文件双击打开失败的问题

Log: 修复超长文件双击打开失败的问题

/review 
@pengfeixx @myk1343 @wyu71

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
